name: chat_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^4.0.3
  shared_preferences: ^2.0.18
  flutter_launcher_icons: ^0.13.1
  image_picker: ^0.8.6+3
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  flutter_chat_bubble: ^2.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  conditional_builder_null_safety: ^0.0.6

  # Firebase
  firebase_storage: ^11.0.14
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  cloud_firestore: ^4.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/app logo.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/app logo.jpg
    - assets/images/camera.png
    - assets/images/add_image.png
