// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7gGzu5b4_0DMyUnCK-m5-X034ncLA_1k',
    appId: '1:985895802536:web:b34fbdb6dde18c8575549d',
    messagingSenderId: '985895802536',
    projectId: 'chatter-app-2ee82',
    authDomain: 'chatter-app-2ee82.firebaseapp.com',
    storageBucket: 'chatter-app-2ee82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAliziR-gGGka-CV7INRWCP646ElfC7gGg',
    appId: '1:985895802536:android:f4916351a886086075549d',
    messagingSenderId: '985895802536',
    projectId: 'chatter-app-2ee82',
    storageBucket: 'chatter-app-2ee82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR3evK5HcwujIuaeu1YryWKW0At3Soaxk',
    appId: '1:985895802536:ios:c3c78660c428557a75549d',
    messagingSenderId: '985895802536',
    projectId: 'chatter-app-2ee82',
    storageBucket: 'chatter-app-2ee82.appspot.com',
    iosClientId: '985895802536-irpelpfhk0d35cfghtlkt0eihsrb0uiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR3evK5HcwujIuaeu1YryWKW0At3Soaxk',
    appId: '1:985895802536:ios:c3c78660c428557a75549d',
    messagingSenderId: '985895802536',
    projectId: 'chatter-app-2ee82',
    storageBucket: 'chatter-app-2ee82.appspot.com',
    iosClientId: '985895802536-irpelpfhk0d35cfghtlkt0eihsrb0uiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
